services:
  gravity_cms.field.reference.widget.sonata_upload:
    class: Gravity\MediaBundle\Field\Type\Reference\Widget\SonataUpload\SonataUploadWidget
    tags:
      - { name: gravity_cms.field.widget }
